import math as m
import os
import shutil
import tempfile
from typing import Collection
import zipfile

from parser import read_java_files
from chunker import chunk_java_ast
from llm_client import review_code
from sonarqube import get_sonar_issues
from vectordb import add_chunk, retrieve


def load_changed_files(extract_folder):
    """
    Reads changed_files.txt generated by Jenkins.
    Returns a set of relative Java file paths.
    """

    changed_file_path = os.path.join(extract_folder, "changed_files.txt")

    if not os.path.exists(changed_file_path):
        print("changed_files.txt not found. Reviewing all Java files.")
        return None

    with open(changed_file_path, "r") as f:
        changed_files = {
            line.strip().replace("\\", "/")
            for line in f
            if line.strip()
        }

    print("Changed files:")
    for file in changed_files:
        print(file)

    return changed_files


def review_project(zip_path):

    extract_folder = tempfile.mkdtemp(prefix="review_")

    try:

        ####################################################
        # Extract ZIP
        ####################################################

        with zipfile.ZipFile(zip_path, "r") as zip_ref:
            zip_ref.extractall(extract_folder)

        ####################################################
        # Read changed_files.txt
        ####################################################

        changed_files = load_changed_files(extract_folder)

        ####################################################
        # Read all Java files
        ####################################################

        all_java_files = read_java_files(extract_folder)

        ####################################################
        # Keep only changed Java files
        ####################################################

        java_files = {}

        for file_path, code in all_java_files.items():

            relative_path = os.path.relpath(
                file_path,
                extract_folder
            ).replace("\\", "/")

            if changed_files is None or relative_path in changed_files:
                java_files[file_path] = code

        print(f"\nReviewing {len(java_files)} changed Java files\n")

        ####################################################
        # Build Vector DB
        ####################################################

        for file_path, code in java_files.items():

            chunks, metadata = chunk_java_ast(code)
            

            for index, chunk in enumerate(chunks):

                add_chunk(
                    id=f"{file_path}_{index}",
                    code=chunk,
                    file=file_path
                )
                print("\nTotal vectors in ChromaDB:")
                print(Collection.count())

        ####################################################
        # Review each chunk
        ####################################################

        reviews = []

        for file_path, code in java_files.items():

            print("Reviewing:", file_path)

            chunks, metadata = chunk_java_ast(code)
            print(f"\nFile: {file_path}")
            print(f"Methods found: {len(metadata)}")

            chunk_reviews = []
            sonar = get_sonar_issues(file_path)

            for i, chunk in enumerate(chunks):
                print(f"Method: {m['method']}  Line: {m['line']}")

                context_chunks = retrieve(chunk)

                context = "\n\n".join(context_chunks)

                review = review_code(
                 file_name=file_path,
                 code=chunk,
                 context=context,
                 sonar_issues=sonar)
                print("\nCurrent Method:")
                print(metadata[i]["method"])

                print("\nContext sent to LLM:")
                print(context[:500])

                chunk_reviews.append({

                    "method": metadata[i]["method"],

                    "line": metadata[i]["line"],

                    "review": review

                })

            reviews.append({

                "file": file_path,

                "chunk_reviews": chunk_reviews

            })

        ####################################################
        # Final Response
        ####################################################

        return {

            "status": "success",

            "files_reviewed": len(java_files),

            "reviews": reviews

        }

    finally:

        shutil.rmtree(extract_folder, ignore_errors=True)