import os
import shutil
import tempfile
import zipfile

from parser import read_java_files
from chunker import chunk_java_ast
from llm_client import review_code
from sonarqube import get_sonar_issues
from vectordb import add_chunk, retrieve, collection  # Explicitly import collection for count track

def load_changed_files(extract_folder):
    """
    Reads changed_files.txt generated by Jenkins.
    Returns a set of relative Java file paths.
    """
    changed_file_path = os.path.join(extract_folder, "changed_files.txt")

    if not os.path.exists(changed_file_path):
        print("changed_files.txt not found. Reviewing all Java files.")
        return None

    with open(changed_file_path, "r") as f:
        # Strip out 'review_package/' or 'backend/' prefix from path names if sent from Jenkins
        changed_files = {
            line.strip().replace("\\", "/").split("review_package/")[-1].split("backend/")[-1]
            for line in f
            if line.strip()
        }

    print("Changed files to filter:")
    for file in changed_files:
        print(f" - {file}")

    return changed_files

def review_project(zip_path):
    extract_folder = tempfile.mkdtemp(prefix="review_")
    reviews = []

    try:
        ####################################################
        # 1. Extract ZIP Archive
        ####################################################
        with zipfile.ZipFile(zip_path, "r") as zip_ref:
            zip_ref.extractall(extract_folder)

        # Track the changed files manifest file
        changed_files = load_changed_files(extract_folder)

        ####################################################
        # 2. Extract and Filter target Java Files
        ####################################################
        all_java_files = read_java_files(extract_folder)
        java_files = {}

        for file_path, code in all_java_files.items():
            # Calculate standard relative path to evaluate against manifest definitions
            relative_path = os.path.relpath(file_path, extract_folder).replace("\\", "/")
            # Remove top folder artifacts from copy processes if present
            clean_rel_path = relative_path.split("review_package/")[-1].split("backend/")[-1]

            if changed_files is None or clean_rel_path in changed_files:
                java_files[file_path] = {
                    "code": code,
                    "relative_path": clean_rel_path
                }

        print(f"\nReviewing {len(java_files)} changed Java files\n")

        ####################################################
        # 3. Process Code, Build Vector DB & Analyze (Single Pass)
        ####################################################
        # First pass: Populate vector DB with code blocks to build context reference
        for file_path, data in java_files.items():
            chunks, metadata = chunk_java_ast(data["code"])
            data["chunks"] = chunks
            data["metadata"] = metadata

            for index, chunk in enumerate(chunks):
                add_chunk(
                    id=f"{data['relative_path']}_{index}",
                    code=chunk,
                    file=data["relative_path"]
                )
        
        print(f"\nTotal vectors inside ChromaDB: {collection.count()}")

        # Second pass: Perform actual code evaluations using complete project maps
        for file_path, data in java_files.items():
            print("Analyzing File:", data["relative_path"])
            
            chunk_reviews = []
            # Pass clean relative path matching SonarQube component strings
            sonar = get_sonar_issues(data["relative_path"])

            for i, chunk in enumerate(data["chunks"]):
                current_meta = data["metadata"][i]
                print(f"-> Method: {current_meta['method']} | Line: {current_meta['line']}")

                # Retrieve code contexts, ignoring vectors derived from the identical target file path
                context_chunks = retrieve(chunk, exclude_file=data["relative_path"])
                context = "\n\n".join(context_chunks)

                # Execute LLM API evaluations
                review = review_code(
                    file_name=data["relative_path"],
                    code=chunk,
                    context=context,
                    sonar_issues=sonar
                )

                chunk_reviews.append({
                    "method": current_meta["method"],
                    "line": current_meta["line"],
                    "review": review
                })

            reviews.append({
                "file": data["relative_path"],
                "chunk_reviews": chunk_reviews
            })

        return {
            "status": "success",
            "files_reviewed": len(java_files),
            "reviews": reviews
        }

    finally:
        shutil.rmtree(extract_folder, ignore_errors=True)
