import os
import shutil
import tempfile
import tarfile

from parser import read_java_files
from chunker import chunk_java_ast
from llm_client import review_code
from sonarqube import get_sonar_issues
from vectordb import add_chunk, retrieve, collection

from java_parser import parse_java_file
from graph.graph_service import (
    store_java,
    get_business_context
)


def load_changed_files(extract_folder):
    """
    Reads changed_files.txt generated by Jenkins.
    Returns set of changed Java files.
    """

    changed_file_path = os.path.join(
        extract_folder,
        "changed_files.txt"
    )


    if not os.path.exists(changed_file_path):

        print(
            "changed_files.txt not found. Reviewing all Java files."
        )

        return None


    with open(changed_file_path, "r") as f:

        changed_files = {
            line.strip()
                .replace("\\", "/")
                .split("review_package/")[-1]
                .split("backend/")[-1]
            for line in f
            if line.strip()
        }


    print("\nChanged Files:")

    for file in changed_files:
        print(" -", file)


    return changed_files



def review_project(tar_path):

    extract_folder = tempfile.mkdtemp(
        prefix="review_"
    )


    reviews = []


    try:


        ##########################################################
        # 1. Extract TAR
        ##########################################################

        print(
            "\n========== EXTRACTING PACKAGE =========="
        )


        with tarfile.open(
            tar_path,
            "r:gz"
        ) as tar_ref:

            tar_ref.extractall(
                extract_folder
            )



        ##########################################################
        # 2. Load Changed Files
        ##########################################################

        changed_files = load_changed_files(
            extract_folder
        )



        ##########################################################
        # 3. Load Jira Story
        ##########################################################

        jira_story = ""


        jira_file = os.path.join(
            extract_folder,
            "jira-story.json"
        )


        if os.path.exists(jira_file):

            with open(
                jira_file,
                "r"
            ) as f:

                jira_story = f.read()


            print(
                "Jira story loaded successfully"
            )

        else:

            print(
                "jira-story.json missing"
            )



        ##########################################################
        # 4. Read Java Files
        ##########################################################

        print(
            "\n========== READING JAVA FILES =========="
        )


        all_java_files = read_java_files(
            extract_folder
        )


        print("==============================")
        print(
            "JAVA FILE TYPE:",
            type(all_java_files)
        )
        print("==============================")



        java_files = {}



        ##########################################################
        # Handle List / Dictionary response
        ##########################################################

        if isinstance(all_java_files, list):


            java_iterator = [

                (
                    item.get("file")
                    or item.get("path"),

                    item.get("code")

                )

                for item in all_java_files

            ]


        else:

            java_iterator = all_java_files.items()



        ##########################################################
        # Filter Changed Files
        ##########################################################

        for file_path, code in java_iterator:


            if not file_path or not code:

                print(
                    "Skipping invalid Java entry"
                )

                continue



            relative_path = os.path.relpath(
                file_path,
                extract_folder
            ).replace("\\", "/")


            clean_path = (
                relative_path
                .split("review_package/")[-1]
                .split("backend/")[-1]
            )



            if (

                changed_files is None

                or

                clean_path in changed_files

            ):


                java_files[file_path] = {


                    "code": code,


                    "relative_path": clean_path,


                    "parsed": None,


                    "chunks": [],


                    "metadata": []

                }



        print(

            f"Reviewing {len(java_files)} changed Java files"

        )



        ##########################################################
        # 5. Build Neo4j Knowledge Graph
        ##########################################################

        print(
            "\n========== BUILDING NEO4J GRAPH =========="
        )


        for file_path, data in java_files.items():


            parsed = parse_java_file(
                data["code"]
            )


            data["parsed"] = parsed



            if parsed:


                store_java(
                    parsed
                )



        print(
            "Neo4j Graph Updated"
        )



        ##########################################################
        # 6. Build ChromaDB Vector Store
        ##########################################################

        print(
            "\n========== BUILDING VECTOR DATABASE =========="
        )



        for file_path, data in java_files.items():


            chunks, metadata = chunk_java_ast(
                data["code"]
            )


            data["chunks"] = chunks

            data["metadata"] = metadata



            for index, chunk in enumerate(chunks):


                add_chunk(

                    id=f"{data['relative_path']}_{index}",

                    code=chunk,

                    file=data["relative_path"]

                )



        print(

            "Total vectors:",

            collection.count()

        )



        ##########################################################
        # 7. AI Review
        ##########################################################

        print(
            "\n========== STARTING AI REVIEW =========="
        )


        for file_path, data in java_files.items():


            print(

                "\nAnalyzing:",

                data["relative_path"]

            )



            ##################################################
            # Sonar Issues
            ##################################################

            sonar = get_sonar_issues(

                data["relative_path"]

            )



            ##################################################
            # Neo4j Business Context
            ##################################################

            business_context = (
                "No business context available."
            )


            parsed = data.get(
                "parsed"
            )



            if parsed:


                business_context = (

                    get_business_context(

                        parsed["name"]

                    )

                    or

                    "No business context available."

                )



            print(
                "\nBusiness Context:"
            )

            print(
                business_context
            )



            chunk_reviews = []



            ##################################################
            # Review each method chunk
            ##################################################

            for i, chunk in enumerate(
                data["chunks"]
            ):


                meta = data["metadata"][i]



                print(

                    f"Method: {meta['method']} "
                    f"Line: {meta['line']}"

                )



                ##################################################
                # RAG Retrieval
                ##################################################

                context_chunks = retrieve(

                    chunk,

                    exclude_file=data["relative_path"]

                )



                rag_context = "\n\n".join(

                    context_chunks

                )



                ##################################################
                # LLM Review
                ##################################################

                review = review_code(

                    file_name=data["relative_path"],

                    code=chunk,

                    context=rag_context,

                    business_context=business_context,

                    sonar_issues=sonar,

                    jira_story=jira_story

                )



                chunk_reviews.append({

                    "method": meta["method"],

                    "line": meta["line"],

                    "review": review

                })



            reviews.append({

                "file": data["relative_path"],

                "chunk_reviews": chunk_reviews

            })



        ##########################################################
        # Final Response
        ##########################################################

        return {

            "status": "success",

            "files_reviewed": len(java_files),

            "reviews": reviews

        }



    finally:


        shutil.rmtree(

            extract_folder,

            ignore_errors=True

        )